#!/bin/bash
date >> /tmp/log-calls
echo $@ >> /tmp/log-calls

if [ "$1" == "init" -a $# -eq 1 ]; then
  echo -n '{
    "status": "Success",
    "capabilities": {
        "attach": false
    }
  }'
  exit 0
fi

MOUNTPATH=$2
if [ "$1" == "attach" -a $# -eq 2 ]; then
  echo -n '{
    "device": "{{.DevicePath}}",
    "status": "Success"
  }'
  exit 0
elif [ "$1" == "detach" -a $# -eq 2 ]; then
  echo -n '{
    "status": "Success"
  }'
  exit 0
elif [ "$1" == "getvolumename" -a $# -eq 4 ]; then
  echo -n '{
    "status": "Success",
    "volume": "fakevolume"
  }'
  exit 0
elif [ "$1" == "isattached" -a $# -eq 2 ]; then
  echo -n '{
    "status": "Success",
    "attached": true
  }'
  exit 0
elif [ "$1" == "unmount" -a $# -eq 2 ]; then
  umount ${MOUNTPATH} 2>/dev/null > /dev/null
  rm -rf "${MOUNTPATH}.img"
  echo -n '{
    "status": "Success",
    "attached": true
  }'
  exit 0
elif [ "$1" == "mount" -a $# -eq 3 ]; then
  mkdir -p ${MOUNTPATH} 2>/dev/null > /dev/null
  dd if=/dev/zero of="${MOUNTPATH}.img" count=204800 2>/dev/null > /dev/null
  mkfs.ext4 -F "${MOUNTPATH}.img"  2>/dev/null > /dev/null
  mount -o loop ${MOUNTPATH}.img ${MOUNTPATH} 2>/dev/null > /dev/null
  echo -n '{
    "status": "Success",
    "attached": true
  }'
  exit 0
fi

echo -n '{
  "status": "Not supported"
}'
exit 1
